apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  type: NodePort 
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30040
      protocol: TCP
  selector:
    name: web
